name: Check on PR
on:
  pull_request:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm i
      - name: Check types
        run: npm run typecheck
      - name: Lint TS/TSX
        run: npm run lintts
      - name: Lint SCSS
        run: npm run lintscss
      - name: Build the app
        run: npm run build
        
